name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: List directory contents
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build API Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.api
          push: false
          tags: research-agent-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Web Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          push: false
          tags: research-agent-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
